# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://www.dencelkbabu.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Dencel K. Babu"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Dencel Kadambethazhathu Babu
author-bio: Passionate about technology. Loves music, travel, and food! # change to false to hide
author-image: profile-pic.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/dencelkbabu
facebook: https://facebook.com/dencelkbabu
instagram: https://instagram.com/dencelkbabu
github: https://github.com/dencelkbabu
linkedin: https://linkedin.com/in/dencelkbabu
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
